apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: blocky
namespace: blocky
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: config.yml
    files:
      - config.yml
    options:
      disableNameSuffixHash: true
