apiVersion: v1
kind: Service
metadata:
  name: blocky-tcp
spec:
  selector:
    app: blocky
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 53
      targetPort: tcp-dns
      protocol: TCP
      name: tcp-dns
    - port: 4000
      targetPort: prometheus
      protocol: TCP
      appProtocol: http
      name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: blocky-udp
spec:
  selector:
    app: blocky
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 53
      targetPort: udp-dns
      protocol: UDP
      name: udp-dns
