apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: mqtt
namespace: mqtt
resources:
  - service.yaml
  - deployment.yaml
configMapGenerator:
  - name: config.yml
    files:
      - config.yml
    options:
      disableNameSuffixHash: true
