apiVersion: v1
kind: Service
metadata:
  name: mochi-mqtt-web
spec:
  selector:
    app: mqtt
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 7980
      targetPort: http-web
      name: http-web
    - port: 1883
      targetPort: tcp-mqtt
      name: tcp-mqtt
    - port: 1882
      targetPort: tcp-ws
      name: tcp-ws
    - port: 1880
      targetPort: tcp-stats
      name: tcp-stats
