apiVersion: v1
kind: Service
metadata:
  name: languagetool-http
spec:
  selector:
    app: languagetool
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 8010
      targetPort: http
