apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          ports:
            - containerPort: 3000
              name: http
          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources/datasource.yml
              subPath: datasource.yml
            - name: pvc
              mountPath: /var/lib/grafana
          env:
            - name: GF_PANELS_DISABLE_SANITIZE_HTML
              value: "true"
            - name: GF_INSTALL_PLUGINS
              value: grafana-piechart-panel
      volumes:
        - name: datasources
          configMap:
            name: datasource.yml
        - name: pvc
          persistentVolumeClaim:
            claimName: grafana-pvc
