apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: grafana
namespace: grafana
resources:
  - service.yaml
  - deployment.yaml
  - persistentvolumeclaim.yaml
configMapGenerator:
  - name: datasource.yml
    files:
      - datasource.yml
    options:
      disableNameSuffixHash: true
