# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes:
    Draculaish:
      #Dracula Colours
      drac-cyan: "#8be9fd"
      drac-green: "#50fa7b" # No good in Light Mode "#53e677"
      drac-orange: "#ffb86c"
      drac-pink: "#ff79c6"
      drac-purple: "#bd93f9"
      drac-red: "#ff5555"
      drac-yellow: "#f1fa8c"
      drac-blue: "#6272a4"

      ##### Common Definitions #####
      # Global Accent Colors
      overlay2: "#9399b2" #reserved
      overlay1: "#7f849c" #reserved

      # Main Interface colors
      primary-color: var(--lavender)
      light-primary-color: var(--lavender)
      primary-background-color: var(--mantle)
      secondary-background-color: var(--crust)
      code-editor-background-color: var(--crust)
      accent-color: var(--peach)

      # Text
      primary-text-color: var(--text)
      secondary-text-color: var(--subtext1)
      text-primary-color: var(--text)
      divider-color: var(--primary-background-color)
      disabled-text-color: var(--surface0)

      # Buttons
      paper-item-icon-color: var(--subtext0)
      paper-item-icon-active-color: var(--primary-color)
      mdc-button-outline-color: var(--overlay0)

      # States and Badges
      state-icon-color: var(--lavender)
      state-icon-active-color: var(--primary-color)
      state-icon-unavailable-color: var(--disabled-text-color)
      state-light-active-color: var(--yellow)

      # Sliders
      paper-slider-knob-color: var(--primary-color)
      paper-slider-knob-start-color: var(--paper-slider-knob-color)
      paper-slider-pin-color: var(--paper-slider-knob-color)
      paper-slider-active-color: var(--light-primary-color)
      paper-slider-secondary-color: var(--light-primary-color)

      # Labels
      label-badge-background-color: var(--surface0)
      label-badge-text-color: var(--text)
      label-badge-red: var(--red)
      label-badge-green: var(--green)
      label-badge-blue: var(--blue)
      label-badge-yellow: var(--yellow)
      label-badge-gray: var(--overlay1)

      # Cards
      card-background-color: var(--base)
      ha-card-background: var(--card-background-color)
      ha-card-border-color: var(--card-background-color)
      ha-card-border-radius: "15px"
      ha-card-box-shadow: 0px 2px 4px 0px rgba(0,0,0,0.16)
      ha-card-border-width: "0px"
      paper-dialog-background-color: var(--overlay0)
      paper-listbox-background-color: var(--overlay0)
      paper-card-background-color: var(--card-background-color)

      # Switches
      switch-checked-button-color: var(--green)
      switch-checked-track-color: var(--surface2)
      switch-checked-color: var(--surface3)
      switch-unchecked-button-color: var(--surface1)
      switch-unchecked-track-color: var(--surface2)
      switch-unchecked-color: var(--surface3)

      # Toggles
      paper-toggle-button-checked-button-color: var(--switch-checked-button-color)
      paper-toggle-button-checked-bar-color: var(--switch-checked-track-color)
      paper-toggle-button-unchecked-button-color: var(--switch-unchecked-button-color)
      paper-toggle-button-unchecked-bar-color: var(--switch-unchecked-track-color)

      # Tables
      table-row-background-color: var(--primary-background-color)
      table-row-alternative-background-color: var(--secondary-background-color)
      data-table-background-color: var(--primary-background-color)

      # Dropdowns
      material-background-color: var(--primary-background-color)
      material-secondary-background-color: var(--secondary-background-color)
      mdc-theme-surface: var(--primary-background-color)

      # Pre/Code
      markdown-code-background-color: var(--surface0)
      #code-editor-background-color: var(--primary-background-color)

      # Checkboxes
      mdc-checkbox-unchecked-color: var(--surface0)
      mdc-checkbox-disable-color: var(--disabled-text-color)
      mdc-select-fill-color: rgba(var(--crust),1)
      mdc-select-ink-color: var(--text)
      mdc-select-label-ink-color: var(--subtext1)
      mdc-select-idle-line-color: var(--text)
      mdc-select-dropdown-icon-color: var(--secondary-text-color)
      mdc-select-hover-line-color: var(--accent-color)
      mdc-text-field-fill-color: var(--mdc-select-fill-color)
      mdc-radio-unchecked-color: var(--subtext1)
      # Inputs
      input-fill-color: var(--secondary-background-color)
      input-dropdown-icon-color: var(--secondary-text-color)
      input-ink-color: var(--primary-text-color)
      input-label-ink-color: var(--secondary-text-color)
      input-idle-line-color: var(--primary-text-color)
      input-hover-line-color: var(--accent-color)

      # Toast
      paper-toast-background-color: var(--overlay0)

      # Colors for Items
      error-color: var(--red)
      warning-color: var(--yellow)
      success-color: var(--green)
      info-color: var(--lavender)
      state-on-color: var(--rgb-green)
      state-off-color: var(--rgb-red)
      rgb-primary-text-color: var(--orange)
      # Breaks Highlighting Code
      #rgb-primary-color: "#f5c2e7ff"
      rgb-accent-color: var(--mauve)
      rgb-state-switch-color: var(--rgb-accent-color)
      rgb-state-light-color: var(--rgb-accent-color)
      rgb-state-fan-color: var(--rgb-accent-color)
      rgb-state-script-color: var(--rgb-accent-color)
      rgb-state-vacuum-color: var(--rgb-accent-color)
      rgb-state-remote-color: var(--rgb-accent-color)
      rgb-state-input-boolean-color: var(--rgb-accent-color)
      rgb-state-humidifier-color: var(--rgb-accent-color)
      rgb-state-cover-color: var(--rgb-accent-color)
      rgb-state-light: var(--rgb-yellow)

      # State Colors - Assorted
      state-update-on-color: var(--peach)
      state-update-active-color: var(--green)
      #state-inactive-color: var(--rgb-state-light)
      state-update-off-color: var(--green)
      default-light-green: var(--drac-green)
      state-active-color: var(--primary-colour)
      state-red-color: var(--red)
      state-green-color: var(--green)
      state-orange-color: var(--peach)
      state-alarm_control_panel-armed_away-color: "var(--state-green-color)"
      state-alarm_control_panel-armed_custom_bypass-color: "var(--state-green-color)"
      state-alarm_control_panel-armed_home-color: "var(--state-green-color)"
      state-alarm_control_panel-armed_night-color: "var(--state-green-color)"
      state-alarm_control_panel-armed_vacation-color: "var(--state-green-color)"
      state-alarm_control_panel-arming-color: "var(--state-orange-color)"
      state-alarm_control_panel-disarming-color: "var(--state-orange-color)"
      state-alarm_control_panel-pending-color: "var(--state-orange-color)"
      state-alarm_control_panel-triggered-color: "var(--state-red-color)"
      state-alert-off-color: var(--paper-item-icon-color)
      state-alert-on-color: "var(--state-red-color)"
      state-automation-active-color: "var(--accent-color)"
      state-binary_sensor-active-color: "var(--accent-color)"
      state-binary_sensor-battery-on-color: "var(--state-red-color)"
      state-binary_sensor-carbon_monoxide-on-color: "var(--state-red-color)"
      state-binary_sensor-gas-on-color: "var(--state-red-color)"
      state-binary_sensor-heat-on-color: "var(--state-red-color)"
      state-binary_sensor-lock-on-color: "var(--state-red-color)"
      state-binary_sensor-moisture-on-color: "var(--state-red-color)"
      state-binary_sensor-problem-on-color: var(--state-red-color)
      state-binary_sensor-safety-on-color: "var(--state-red-color)"
      state-binary_sensor-smoke-on-color: "var(--state-red-color)"
      state-binary_sensor-sound-on-color: "var(--state-red-color)"
      state-binary_sensor-tamper-on-color: "var(--state-red-color)"
      state-climate-auto-color: "var(--accent-color)"
      state-climate-cool-color: "var(--accent-color)"
      state-climate-dry-color: "var(--accent-color)"
      state-climate-fan_only-color: "var(--accent-color)"
      state-climate-heat-color: "var(--state-orange-color)"
      state-climate-heat-cool-color: "var(--accent-color)"
      state-cover-active-color: "var(--accent-color)"
      state-device_tracker-active-color: "var(--accent-color)"
      state-device_tracker-home-color: "var(--accent-color)"
      state-fan-active-color: "var(--accent-color)"
      state-group-active-color: "var(--accent-color)"
      state-humidifier-active-color: "var(--accent-color)"
      state-input_boolean-active-color: "var(--accent-color)"
      state-lock-jammed-color: "var(--state-red-color)"
      state-lock-locked-color: "var(--accent-color)"
      state-lock-pending-color: "var(--state-orange-color)"
      state-lock-unlocked-color: var(--paper-item-icon-color)
      state-media_player-active-color: "var(--accent-color)"
      state-person-active-color: "var(--accent-color)"
      state-person-home-color: "var(--accent-color)"
      state-plant-active-color: "var(--state-red-color)"
      state-siren-active-color: "var(--state-red-color)"
      state-sun-above_horizon-color: "var(--amber-color)"
      state-sun-below_horizon-color: "var(--indigo-color)"
      state-switch-active-color: "var(--accent-color)"
      state-vacuum-active-color: "var(--accent-color)"
      state-sensor-battery-high-color: "var(--accent-color)"
      state-sensor-battery-low-color: "var(--state-red-color)"
      state-sensor-battery-medium-color: "var(--state-orange-color)"
      # Mushroom Colors
      mush-rgb-red: 255, 085, 085
      mush-rgb-pink: 255, 121, 198
      mush-rgb-purple: 172, 146, 196
      mush-rgb-deep-purple: 219, 089, 161 #Uses mauve
      mush-rgb-indigo: 099, 144, 164
      mush-rgb-blue: 097, 143, 202
      mush-rgb-light-blue: 117, 199, 235
      mush-rgb-cyan: 125, 208, 227
      mush-rgb-teal: 131, 207, 207
      mush-rgb-green: 074, 216, 104 #Draculaish-light-green
      mush-rgb-light-green: 083, 213, 119 #Draculaish-dark-green
      mush-rgb-lime: 083, 213, 119 #Dracula-green
      mush-rgb-yellow: 252, 223, 093
      mush-rgb-amber: 251, 182, 108
      mush-rgb-orange: 251, 182, 71
      mush-rgb-deep-orange: 255, 156, 26
      mush-rgb-brown: 121, 85, 72
      mush-rgb-grey: 127, 132, 156 #overlay1
      mush-rgb-blue-grey: 98, 114, 164 #Dracula-comment
      mush-rgb-black: 33, 34, 44 #dark-crust
      mush-rgb-white: 248, 248, 242 #dracula-white

      #Mushroom Card States
      mush-rgb-info: var(--mush-rgb-blue)
      mush-rgb-success: var(--mush-rgb-green)
      mush-rgb-warning: var(--mush-rgb-orange)
      mush-rgb-danger: var(--mush-rgb-red)

      mush-rgb-state-fan: var(--mush-rgb-green)
      mush-rgb-state-light: var(--mush-rgb-orange)
      mush-rgb-state-entity: var(--mush-rgb-blue)
      mush-rgb-state-switch: var(--mush-rgb-blue)

      mush-rgb-state-alarm-disarmed: var(--mush-rgb-info)
      mush-rgb-state-alarm-armed: var(--mush-rgb-success)
      mush-rgb-state-alarm-triggered: var(--mush-rgb-danger)

      mush-rgb-state-person-home: var(--mush-rgb-success)
      mush-rgb-state-person-not-home: var(--mush-rgb-danger)
      mush-rgb-state-person-zone: var(--mush-rgb-info)
      mush-rgb-state-person-unknown: var(--mush-rgb-grey)

      mush-rgb-state-cover-open: var(--mush-rgb-blue)
      mush-rgb-state-cover-closed: var(--mush-rgb-disabled)

      mush-rgb-state-climate-auto: var(--mush-rgb-green);
      mush-rgb-state-climate-cool: var(--mush-rgb-blue);
      mush-rgb-state-climate-dry: var(--mush-rgb-orange);
      mush-rgb-state-climate-fan-only: var(--mush-rgb-blue-grey);
      mush-rgb-state-climate-heat: var(--mush-rgb-deep-orange);
      mush-rgb-state-climate-heat-cool: var(--mush-rgb-green);
      mush-rgb-state-climate-idle: var(--mush-rgb-grey);
      mush-rgb-state-climate-off: var(--mush-rgb-disabled);

      modes:
        light:
          ##### LIGHT MODE #####
          ##### Color Vars #####
          text: "#474A54"
          text-dark: "#6272a4" #common - dracula comment - not in use

          subtext1: "#72778a"
          subtext0: "#a6adc8"

          overlay0: "#e8e8e3"

          surface2: "#45475a"
          surface1: "#585b70"
          surface0: "#e0e0dc" #same as crust

          base: "#f0f0eb"
          mantle: "#e8e8e3"
          crust: "#e0e0dc"

          #Draculaish-Light Colours
          rosewater: "#ffcce9"
          flamingo: "#ffb0dd"
          pink: "#ff79c6"
          mauve: "#db5ba1"
          red: "#ff5555"
          maroon: "#db5c5c"
          peach: "#ffb86c"
          yellow: "#fcdf5d"
          green: "#4ad868"
          teal: "#84d0cf"
          sky: "#7dd0e3"
          sapphire: "#74c7ec"
          blue: "#5e91d6"
          lavender: "#bd93f9"

          ##### Draculaish-Light Definitions #####
          # Text
          primary-text-color: var(--text-dark)
          secondary-text-color: var(--text-dark)
          text-primary-color: var(--text)
          divider-color: var(--primary-background-color)
          disabled-text-color: var(--surface0)

          # Header
          app-header-background-color: var(--base)
          app-header-text-color: var(--subtext0)
          app-header-selection-bar-color: var(--primary-color)
          app-header-edit-background-color: var(--crust)
          app-header-edit-text-color: var(--text-dark)

          # Sidebar
          sidebar-background-color: var(--crust)
          sidebar-selected-background-color: var(--primary-background-color)
          sidebar-icon-color: var(--text-dark)
          sidebar-text-color: var(--text-dark)
          sidebar-selected-icon-color: var(--primary-color)
          sidebar-selected-text-color: var(--primary-color)
          sidebar-menu-button-text-color: var(--text-dark)

        dark:
          ##### DARK  MODE #####
          ##### Color Vars #####
          text: "#f8f8f2"
          text-dark: "#6272a4"

          subtext1: "#e8e8e3"
          subtext0: "#a6adc8"

          overlay0: "#6c7086"

          surface2: "#585b70"
          surface1: "#45475a"
          surface0: "#313244"

          base: "#343746"
          mantle: "#282a36"
          crust: "#21222c"
          surface: "#70708a"

          #Draculaish-Dark Colours
          rosewater: "#ffcce9"
          flamingo: "#ffb0dd"
          pink: "#ff79c6"
          mauve: "#db5ba1"
          red: "#ff5555"
          maroon: "#db5ba1"
          peach: "#ffb86c"
          yellow: "#fae47f"
          green: "#53e677"
          teal: "#9bd6cf"
          sky: "#8be9fd"
          sapphire: "#74c7ec"
          blue: "#5e91d6"
          lavender: "#bd93f9"

          ##### Draculaish-Dark Definitions #####
          # Header
          app-header-background-color: var(--base)
          app-header-text-color: var(--subtext0)
          app-header-selection-bar-color: var(--primary-color)
          app-header-edit-background-color: var(--crust)
          app-header-edit-text-color: var(--subtext1)

          # Sidebar
          sidebar-background-color: var(--crust)
          sidebar-selected-background-color: var(--primary-background-color)
          sidebar-icon-color: var(--text-dark)
          sidebar-text-color: var(--subtext0)
          sidebar-selected-icon-color: var(--primary-color)
          sidebar-selected-text-color: var(--primary-color)
          sidebar-menu-button-text-color: var(--text-dark)

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
