apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
spec:
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
        - name: homeassistant
          image: ghcr.io/home-assistant/home-assistant:stable
          ports:
            - containerPort: 8123
              name: http
          env:
            - name: TZ
              value: Asia/Tokyo
          volumeMounts:
            - mountPath: /config
              name: config
            - name: configuration-yaml
              mountPath: /config/configuration.yaml
              subPath: configuration.yaml
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - NET_BROADCAST
      hostNetwork: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homeassistant-config
        - name: configuration-yaml
          configMap:
            name: configuration.yaml
