apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: homeassistant
namespace: homeassistant
resources:
  - deployment.yaml
  - persistentvolumeclaim.yaml
configMapGenerator:
  - name: configuration.yaml
    files:
      - configuration.yaml
    options:
      disableNameSuffixHash: true
