apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: homeassistant
namespace: homeassistant
resources:
  - service.yaml
  - deployment.yaml
  - persistentvolumeclaim.yaml
