apiVersion: v1
kind: Service
metadata:
  name: homeassistant
spec:
  selector:
    app: homeassistant
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 8123
      targetPort: http
