apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: prometheus
namespace: prometheus
resources:
  - service.yaml
  - deployment.yaml
  - persistentvolumeclaim.yaml
configMapGenerator:
  - name: prometheus.yml
    files:
      - prometheus.yml
    options:
      disableNameSuffixHash: true
